sudo: required

language: node_js
node_js:
  - "8"

script:
  - npm install
  - npm run build

cache:
  directories:
    - ui-automation/node_modules

after_success:
  - ./firebase_deploy.sh $TRAVIS_BRANCH $FIREBASE_TOKEN_PROD $FIREBASE_PROJECT_PROD
