sudo: required

language: node_js
node_js:
  - "8"

script:
  - npm install
  - npm run build

cache:
  directories:
    - ui-automation/node_modules

after_success:
    - npm run deploy-storybook
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      npm publish
    fi
