sudo: required

language: node_js
node_js:
  - "8"

script:
  - npm install
  - npm run build

cache:
  directories:
    - ui-automation/node_modules

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      npm publish;
      npm run deploy-storybook;
    fi
